### ISSUE TITLE
Grading Overview

### ISSUE THREAD

**Issue by Lucav17** [bigbhowell/vidbits#1]
### Criteria 1: Mongoose Model Implementation
* _Score Level:_  4/4
* _Comment(s):_  The Video model was well structured! One thing I would include is also a timestamp just so you can see when each video was created!
 
### Criteria 2: Implementation of API Specification and Functionality
* _Score Level:_ 4
* _Comment(s):_  Great job! The API's do as the spec was asked, and your code followed the correct implementation
 
### Criteria 3: Single-Item Server Test Cases Implementation
* _Score Level:_ 4
* _Comment(s):_ You did a good job passing test cases!
 
### Criteria 4: Handlebars View Implementation
* _Score Level:_ 4
* _Comment(s):_  The layout itself is simple, but shows an understanding of how to create a template and expose it out to be used by the UI.

### Criteria 5: Implementation of Model and Server Test Cases and All Tests Passing
* _Score Level:_ 4
* _Comment(s):_  Great job handling test cases!

### Criteria 6: Implementation of Feature Test Cases and All Tests Passing
* _Score Level:_ 4
* _Comment(s):_ Great job handling test cases!
 
### Overall Score: 24/24
Great job overall! this shows a great understanding of test-driven development and creating a backend API layer!

**Comment by bigbhowell** [comment]
Thanks for the review!
